config/routes.rb
Rails.application.routes.draw do

  root 'visitors#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :projects
  resources :documents
  resources :contacts
  resources :lessors 
  resources :owners
  resources :deeds
  resources :lawfirms
  resources :companies
  resources :servicers
  resources :clients
  resources :employees
  resources :parcels
  resources :leases
  resources :lease_provisons
  resources :lawyers
  resources :services_users
  resources :abstractors
  resources :service_transitions
  resources :dashboards, only: [:index]
  resources :title_abstracts
  resources :abstractor_dashboards, only: [:index]
  resources :absdashes, only: [:index]

  resources :services do
    member do
      put "accept" => "services#accept", as: :accept
    end

    resources :abstractors  do
       member do
         put "assign" => "abstractors#assign", as: :assign
       end
    end
  end

  devise_for :users
  resources :users

end

app/models/absdash.rb
class Absdash < ActiveRecord::Base
  # class for Abstractor Dashboard
end

app/models/client.rb
class Client < Company
  has_many :employees
  has_many :projects
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :employees
  has_and_belongs_to_many :services, through: :companies_services
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :project
  belongs_to :lease
  belongs_to :service
  belongs_to :parcel


   def name
     [first_name, last_name].compact.join(' ')
   end

   def alt_name
     [last_name, first_name].compact.join(', ')
   end

end
 

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/deed.rb
class Deed < ActiveRecord::Base

  has_many :deed_title_abstracts
  has_many :title_abstracts, through: :deed_title_abstracts
  has_many :documents
  accepts_nested_attributes_for  :documents
end

app/models/document.rb
class Document < ActiveRecord::Base

  protokoll :file_name, :pattern => "DOC-%y-%m-####"

  belongs_to :service
  has_many :user_documents
  has_and_belongs_to_many :users, through: :user_documents
  belongs_to :lease
  belongs_to :deed
  belongs_to :title_abstract
  belongs_to :project

  mount_uploader :doc, DocUploader
end

app/models/employee.rb
class Employee < User

  belongs_to :company
  has_many :services, through: :services_users

end

app/models/flow.rb
class Flow < ActiveRecord::Base

 belongs_to :service
 belongs_to :lease



end

app/models/general.rb
class General < Contact

  belongs_to :project
  belongs_to :service

end

app/models/lawfirm.rb
class Lawfirm < ActiveRecord::Base
  has_many :lawyers
  has_many :services

end

app/models/lawyer.rb
class Lawyer < User

  belongs_to :lawfirm
  has_and_belongs_to_many  :services , through: :services_users
  has_and_belongs_to_many :title_abstracts, through: :users_abstracts
end

app/models/lease.rb
class Lease < ActiveRecord::Base

  has_many :services
  has_many :flows
  has_many :parcels
  has_many :documents
  has_many :contacts
  has_many :owners
  has_many :lessors
  has_many :lease_provisons

  belongs_to :project

  accepts_nested_attributes_for :owners
  accepts_nested_attributes_for :lessors
  accepts_nested_attributes_for :parcels
  accepts_nested_attributes_for :documents
  accepts_nested_attributes_for :lease_provisons

end

app/models/lessee.rb
class Lessee < ActiveRecord::Base
  belongs_to :service
  belongs_to :lease
end

app/models/lessor.rb
class Lessor < Contact

  belongs_to :project
  belongs_to :lease
  belongs_to :service

end

app/models/owner.rb
class Owner < Contact

  belongs_to :project 
  belongs_to :lease
  belongs_to :parcel 
  belongs_to :service

end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
  belongs_to :service
  belongs_to :lease
  has_one :title_abstract
  belongs_to :project 
  has_many :owners
  accepts_nested_attributes_for :owners
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :leases
  has_many :services
  has_many :parcels
  has_many :contacts
  has_many :owners
  has_many :lessors
  has_many :title_abstracts
  has_many :documents

  has_paper_trail

end

app/models/service.rb
class Service < ActiveRecord::Base

  protokoll :sr_name, :pattern => "SR-%y-%m-####"

 include Statesman::Adapters::ActiveRecordQueries

 has_many :service_transitions

 has_many :flows
 has_many :parcels
 has_many :contacts
 has_many :lessors
 has_many :documents
 has_many :title_abstracts
 has_and_belongs_to_many :users, through: :services_users
 has_and_belongs_to_many :employees, through: :services_users
 has_and_belongs_to_many :lawyers, through: :services_users
 has_and_belongs_to_many :abstractors, through: :services_users
 has_and_belongs_to_many :companies, through: :services_companies
 has_and_belongs_to_many :servicers, through: :companies_services
 belongs_to :project
 belongs_to :lease

 accepts_nested_attributes_for :documents


 has_paper_trail

 # Initialize the state machine

 def state_machine
  @state_machine ||= RequestStateMachine.new(self, transition_class: ServiceTransition)
 end

 # Optionally delegate some methods
 delegate :can_transition_to?, :transition_to!, :transition_to, :current_state, :allowed_transitions,
          to: :state_machine

 private


 def self.transition_class
  ServiceTransition
 end


 def self.initial_state
   RequestStateMachine.initial_state
 end
end

app/models/servicer.rb
class Servicer < Company
  has_many :employees
  has_many :projects
  has_and_belongs_to_many :services, through: :services_users
  has_and_belongs_to_many :services, through: :companies_services
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  enum role: [:user, :lawgix, :admin]
  has_paper_trail

  belongs_to :company
  has_many :user_documents
  has_and_belongs_to_many :documents, through: :user_documents
  has_and_belongs_to_many :services, through: :services_users


  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  def name
    [first_name, last_name].compact.join(' ')
  end


devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def new
    @employee = Employee.new
  end

  def show
    @employee = Employee.find(params[:id])
    # authorize @company
  end

  def index
    @employees =  Employee.all
  end

  def create
    @employee = Employee.new(secure_params)
    @employee.save

    redirect_to employees_path
  end

  private

  def secure_params
    params.require(:employee).permit(:first_name, :last_name,:company_id, :password, :name, :city, :state, :zip, :phone, :email)
  end
end

app/views/employees/_employee.html.erb
<td>
  <%= link_to employee.email, employee %>
</td>
<td>
  <%= form_for(employee) do |f| %>
    <%= f.select(:role, Employee.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete client", employee_path(employee), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless employee == current_user %>
</td>

app/views/employees/index.html.erb
<div class="flex-boxes">
  <dic class="flex-box flex-box-full">
<div id="client-index">
  <h1>Employees</h1>
  <table>
    <thead>
    <tr>
      <td>Name</td>
      <td>Company</td>
      <td>Phone</td>
      <td>Email<td>
    </tr>
    </thead>
    <tbody>
    <% @employees.each do |employee| %>
        <tr>
          <% company = employee.company %>
          <td><%= link_to(employee.last_name, employee_path(employee))  %></td>
          <td><%= link_to(company.name, company_path(company))  %></td>
          <td><%= employee.phone %></td>
          <td><%= employee.email %><td>
        </tr>
       <% end %>
     </tbody>
   </table>
 </div>
 </div>
</div>

app/views/employees/new.html.erb
<div id="new_client_form">
  <h1>New Employee </h1>
  <fieldset>
    <%= simple_form_for @employee  do |f| %>
        <%= f.association :company %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
        <%= f.label :phone %>
        <%= f.text_field :phone %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.text_field :password %>
        <%= f.submit 'Create Employee' %>
        </div>
        </li>
    <% end %>
    </fieldset>
    </div>

app/views/employees/show.html.erb
<div class="flex-boxes">
  <div class="flex-box flex-box-full">
    <h3>Employee</h3>
    <%= simple_form_for @employee  do |f| %>
        <%= f.association :company %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
        <%= f.label :phone %>
        <%= f.text_field :phone %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.text_field :password %>
        <%= f.submit 'Create Employee' %>
        </div>
        </li>
    <% end %>
 </div>
</div>