config/routes.rb
Rails.application.routes.draw do

  root 'visitors#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :projects
  resources :documents
  resources :contacts
  resources :lessors 
  resources :owners
  resources :deeds
  resources :lawfirms
  resources :companies
  resources :servicers
  resources :clients
  resources :employees
  resources :parcels
  resources :leases
  resources :lease_provisons
  resources :lawyers
  resources :services_users
  resources :abstractors
  resources :service_transitions
  resources :dashboards, only: [:index]
  resources :title_abstracts
  resources :abstractor_dashboards, only: [:index]
  resources :absdashes, only: [:index]

  resources :services do
    member do
      put "accept" => "services#accept", as: :accept
    end

    resources :abstractors  do
       member do
         put "assign" => "abstractors#assign", as: :assign
       end
    end
  end

  devise_for :users
  resources :users

end

app/models/absdash.rb
class Absdash < ActiveRecord::Base
  # class for Abstractor Dashboard
end

app/models/abstractor.rb
class Abstractor < User
  has_and_belongs_to_many :title_abstracts, through: :title_abstracts_users
  has_and_belongs_to_many :services, through: :services_users
end

app/models/client.rb
class Client < Company
  has_many :employees
  has_many :projects
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :employees
  has_and_belongs_to_many :services, through: :companies_services
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :project
  belongs_to :lease
  belongs_to :service
  belongs_to :parcel


   def name
     [first_name, last_name].compact.join(' ')
   end

   def alt_name
     [last_name, first_name].compact.join(', ')
   end

end
 

app/models/deed.rb
class Deed < ActiveRecord::Base

  has_many :deed_title_abstracts
  has_many :title_abstracts, through: :deed_title_abstracts
  has_many :documents
  accepts_nested_attributes_for  :documents
end

app/models/document.rb
class Document < ActiveRecord::Base

  protokoll :file_name, :pattern => "DOC-%y-%m-####"

  belongs_to :service
  has_many :user_documents
  has_and_belongs_to_many :users, through: :user_documents
  belongs_to :lease
  belongs_to :deed
  belongs_to :title_abstract
  belongs_to :project

  mount_uploader :doc, DocUploader
end

app/models/employee.rb
class Employee < User

  belongs_to :company
  has_many :services, through: :services_users

end

app/models/flow.rb
class Flow < ActiveRecord::Base

 belongs_to :service
 belongs_to :lease



end

app/models/general.rb
class General < Contact

  belongs_to :project
  belongs_to :service

end

app/models/lawfirm.rb
class Lawfirm < ActiveRecord::Base
  has_many :lawyers
  has_many :services

end

app/models/lawyer.rb
class Lawyer < User

  belongs_to :lawfirm
  has_and_belongs_to_many  :services , through: :services_users
  has_and_belongs_to_many :title_abstracts, through: :users_abstracts
end

app/models/lease.rb
class Lease < ActiveRecord::Base

  has_many :services
  has_many :flows
  has_many :parcels
  has_many :documents
  has_many :contacts
  has_many :owners
  has_many :lessors
  has_many :lease_provisons

  belongs_to :project

  accepts_nested_attributes_for :owners
  accepts_nested_attributes_for :lessors
  accepts_nested_attributes_for :parcels
  accepts_nested_attributes_for :documents
  accepts_nested_attributes_for :lease_provisons

end

app/models/lessee.rb
class Lessee < ActiveRecord::Base
  belongs_to :service
  belongs_to :lease
end

app/models/lessor.rb
class Lessor < Contact

  belongs_to :project
  belongs_to :lease
  belongs_to :service

end

app/models/owner.rb
class Owner < Contact

  belongs_to :project 
  belongs_to :lease
  belongs_to :parcel 
  belongs_to :service

end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
  belongs_to :service
  belongs_to :lease
  has_one :title_abstract
  belongs_to :project 
  has_many :owners
  accepts_nested_attributes_for :owners
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :leases
  has_many :services
  has_many :parcels
  has_many :contacts
  has_many :owners
  has_many :lessors
  has_many :title_abstracts
  has_many :documents

  has_paper_trail

end

app/models/service.rb
class Service < ActiveRecord::Base

  protokoll :sr_name, :pattern => "SR-%y-%m-####"

 include Statesman::Adapters::ActiveRecordQueries

 has_many :service_transitions

 has_many :flows
 has_many :parcels
 has_many :contacts
 has_many :lessors
 has_many :documents
 has_many :title_abstracts
 has_and_belongs_to_many :users, through: :services_users
 has_and_belongs_to_many :employees, through: :services_users
 has_and_belongs_to_many :lawyers, through: :services_users
 has_and_belongs_to_many :abstractors, through: :services_users
 has_and_belongs_to_many :companies, through: :services_companies
 has_and_belongs_to_many :servicers, through: :companies_services
 belongs_to :project
 belongs_to :lease

 accepts_nested_attributes_for :documents


 has_paper_trail

 # Initialize the state machine

 def state_machine
  @state_machine ||= RequestStateMachine.new(self, transition_class: ServiceTransition)
 end

 # Optionally delegate some methods
 delegate :can_transition_to?, :transition_to!, :transition_to, :current_state, :allowed_transitions,
          to: :state_machine

 private


 def self.transition_class
  ServiceTransition
 end


 def self.initial_state
   RequestStateMachine.initial_state
 end
end

app/models/servicer.rb
class Servicer < Company
  has_many :employees
  has_many :projects
  has_and_belongs_to_many :services, through: :services_users
  has_and_belongs_to_many :services, through: :companies_services
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  enum role: [:user, :lawgix, :admin]
  has_paper_trail

  belongs_to :company
  has_many :user_documents
  has_and_belongs_to_many :documents, through: :user_documents
  has_and_belongs_to_many :services, through: :services_users


  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  def name
    [first_name, last_name].compact.join(' ')
  end


devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/abstractors_controller.rb
class AbstractorsController < ApplicationController

  before_filter :authenticate_user!


  # after_action :verify_authorized


  def new
    @abstractor = Abstractor.new
    # authorize Abstractor
  end

  def show
    @abstractor = Abstractor.find(params[:id])
    # authorize @abstractor
  end

  def index
    @abstractors =  Abstractor.all
    # authorize Abstractor
  end

  def assign
    @service = Service.find(params[:service_id])
    @user = User.find(params[:id])
    @service.users << @user
    @service.transition_to!(:assigned)
    redirect_to dashboards_path
  end

  def dispatcher
   @service = ServicesUsers.create!(:service_id => params[:service], :user_id => params[:abstractors])
   @service.save
  end

  def create
    @abstractor = Abstractor.new(secure_params)
    @abstractor.save

    redirect_to abstractors_path
  end

  def update
    @abstractor = Abstractor.find(params[:id])
    authorize Abstractor
    if @abstractor.update_attributes(secure_params)
      redirect_to abstractors_path, :notice => "Abstractor updated."
    else
      redirect_to abstractors_path, :alert => "Unable to update abstractor."
    end
  end


  private

  def secure_params
    params.require(:abstractor).permit(:first_name, :last_name, :password, :name, :city, :state, :zip, :phone, :email)
  end
end

app/views/abstractors/_abstractor.html.erb
<td>
  <%= link_to abstractor.email, abstractor %>
</td>
<td>
  <%= form_for(abstractor) do |f| %>
    <%= f.select(:role, Abstractor.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete Abstractor", abstractor_path(abstractor), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless abstractor == current_user %>
</td>

app/views/abstractors/index.html.erb
<div class="flex-boxes">
  <a href="javascript:void(0)" class="flex-box flex-box-full">
      <h2 class="flex-title">Abstractors</h2>
  <table>
    <thead>
    <tr>
      <td>Name</td>
      <td>Phone</td>
      <td>Email<td>
    </tr>
    </thead>
    <tbody>
    <% @abstractors.each do |abstractor| %>
        <tr>
          <td><%= link_to(abstractor.name, abstractor_path(abstractor))  %></td>
          <td><%= abstractor.phone %></td>
          <td><%= abstractor.email %><td>
        </tr>
       <% end %>
     </tbody>
   </table>
  </a>
</div>

app/views/abstractors/new.html.erb
<div class="flex-boxes">
  <div class="flex-box flex-box-full">
  <h2 class="flex-title"> New Abstractor </h1>
    <%= simple_form_for @abstractor do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
        <%= f.label :phone %>
        <%= f.text_field :phone %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.text_field :password %>
        <%= f.submit 'Create Abstractor' %>
    <% end %>
    </div>
  </div>
</div>

app/views/abstractors/show.html.erb
<div class="flex-boxes">
  <div class="flex-box flex-box-full">
    <h3>Abstractor</h3>
    <%= simple_form_for @abstractor do |f| %>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
        <%= f.label :phone %>
        <%= f.text_field :phone %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.text_field :password %>
        <%= f.submit 'Update Abstractor' %>
    <% end %>
 </div>
</div>