config/routes.rb
Rails.application.routes.draw do

  root 'visitors#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :projects
  resources :documents
  resources :contacts
  resources :lessors 
  resources :owners
  resources :deeds
  resources :lawfirms
  resources :companies
  resources :servicers
  resources :clients
  resources :employees
  resources :parcels
  resources :leases
  resources :lease_provisons
  resources :lawyers
  resources :services_users
  resources :abstractors
  resources :service_transitions
  resources :dashboards, only: [:index]
  resources :title_abstracts
  resources :abstractor_dashboards, only: [:index]
  resources :absdashes, only: [:index]

  resources :services do
    member do
      put "accept" => "services#accept", as: :accept
    end

    resources :abstractors  do
       member do
         put "assign" => "abstractors#assign", as: :assign
       end
    end
  end

  devise_for :users
  resources :users

end

app/models/absdash.rb
class Absdash < ActiveRecord::Base
  # class for Abstractor Dashboard
end

app/models/client.rb
class Client < Company
  has_many :employees
  has_many :projects
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :employees
  has_and_belongs_to_many :services, through: :companies_services
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :project
  belongs_to :lease
  belongs_to :service
  belongs_to :parcel


   def name
     [first_name, last_name].compact.join(' ')
   end

   def alt_name
     [last_name, first_name].compact.join(', ')
   end

end
 

app/models/deed.rb
class Deed < ActiveRecord::Base

  has_many :deed_title_abstracts
  has_many :title_abstracts, through: :deed_title_abstracts
  has_many :documents
  accepts_nested_attributes_for  :documents
end

app/models/document.rb
class Document < ActiveRecord::Base

  protokoll :file_name, :pattern => "DOC-%y-%m-####"

  belongs_to :service
  has_many :user_documents
  has_and_belongs_to_many :users, through: :user_documents
  belongs_to :lease
  belongs_to :deed
  belongs_to :title_abstract
  belongs_to :project

  mount_uploader :doc, DocUploader
end

app/models/employee.rb
class Employee < User

  belongs_to :company
  has_many :services, through: :services_users

end

app/models/flow.rb
class Flow < ActiveRecord::Base

 belongs_to :service
 belongs_to :lease



end

app/models/general.rb
class General < Contact

  belongs_to :project
  belongs_to :service

end

app/models/lawfirm.rb
class Lawfirm < ActiveRecord::Base
  has_many :lawyers
  has_many :services

end

app/models/lawyer.rb
class Lawyer < User

  belongs_to :lawfirm
  has_and_belongs_to_many  :services , through: :services_users
  has_and_belongs_to_many :title_abstracts, through: :users_abstracts
end

app/models/lease.rb
class Lease < ActiveRecord::Base

  has_many :services
  has_many :flows
  has_many :parcels
  has_many :documents
  has_many :contacts
  has_many :owners
  has_many :lessors
  has_many :lease_provisons

  belongs_to :project

  accepts_nested_attributes_for :owners
  accepts_nested_attributes_for :lessors
  accepts_nested_attributes_for :parcels
  accepts_nested_attributes_for :documents
  accepts_nested_attributes_for :lease_provisons

end

app/models/lessee.rb
class Lessee < ActiveRecord::Base
  belongs_to :service
  belongs_to :lease
end

app/models/lessor.rb
class Lessor < Contact

  belongs_to :project
  belongs_to :lease
  belongs_to :service

end

app/models/owner.rb
class Owner < Contact

  belongs_to :project 
  belongs_to :lease
  belongs_to :parcel 
  belongs_to :service

end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
  belongs_to :service
  belongs_to :lease
  has_one :title_abstract
  belongs_to :project 
  has_many :owners
  accepts_nested_attributes_for :owners
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :leases
  has_many :services
  has_many :parcels
  has_many :contacts
  has_many :owners
  has_many :lessors
  has_many :title_abstracts
  has_many :documents

  has_paper_trail

end

app/models/service.rb
class Service < ActiveRecord::Base

  protokoll :sr_name, :pattern => "SR-%y-%m-####"

 include Statesman::Adapters::ActiveRecordQueries

 has_many :service_transitions

 has_many :flows
 has_many :parcels
 has_many :contacts
 has_many :lessors
 has_many :documents
 has_many :title_abstracts
 has_and_belongs_to_many :users, through: :services_users
 has_and_belongs_to_many :employees, through: :services_users
 has_and_belongs_to_many :lawyers, through: :services_users
 has_and_belongs_to_many :abstractors, through: :services_users
 has_and_belongs_to_many :companies, through: :services_companies
 has_and_belongs_to_many :servicers, through: :companies_services
 belongs_to :project
 belongs_to :lease

 accepts_nested_attributes_for :documents


 has_paper_trail

 # Initialize the state machine

 def state_machine
  @state_machine ||= RequestStateMachine.new(self, transition_class: ServiceTransition)
 end

 # Optionally delegate some methods
 delegate :can_transition_to?, :transition_to!, :transition_to, :current_state, :allowed_transitions,
          to: :state_machine

 private


 def self.transition_class
  ServiceTransition
 end


 def self.initial_state
   RequestStateMachine.initial_state
 end
end

app/models/servicer.rb
class Servicer < Company
  has_many :employees
  has_many :projects
  has_and_belongs_to_many :services, through: :services_users
  has_and_belongs_to_many :services, through: :companies_services
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  enum role: [:user, :lawgix, :admin]
  has_paper_trail

  belongs_to :company
  has_many :user_documents
  has_and_belongs_to_many :documents, through: :user_documents
  has_and_belongs_to_many :services, through: :services_users


  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  def name
    [first_name, last_name].compact.join(' ')
  end


devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

end

app/views/shared/_flashes.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

app/views/shared/_nav.erb
<header class="navigation">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <%= image_tag('lawgix.png') %>
    </a>
    <a href="" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link more"><a href="javascript:void(0)"><%= link_to "Services", services_path %></a>
          <ul class="submenu">
            <li><%= link_to "Service Requests", services_path %></li>
            <li><%= link_to "New Service Request",new_service_path %></li>
            <li><%= link_to "Request States", service_transitions_path %>
            </li>
          </ul>
        </li>
      <li class="nav-link more"><a href="javascript:void(0)"> Abstractors</a>
          <ul class="submenu">
            <li><%= link_to "Abstractor Dashboard", contacts_path %></li>
            <li><%= link_to "New Abstractor",new_contact_path %></li>
            <li><%= link_to "New Title Abstract",new_title_abstract_path %></li>
            <li><%= link_to "Title Abstracts",title_abstracts_path %></li>
            </li>
          </ul>
          </li>
        <li class="nav-link more"><a href="javascript:void(0)"> Lawyers</a>
          <ul class="submenu">
            <li><%= link_to "Lawyer Dashboard", lawyers_path %></li>
            <li><%= link_to "New Lawyer",new_lawyer_path %></li>
            <li><%= link_to "Law Firms",lawfirms_path %></li>
            <li><%= link_to "New Law Firm",new_lawfirm_path %></li>
            </li>
          </ul>
          </li>
        <li class="nav-link more"><a href="javascript:void(0)">Clients</a>
          <ul class="submenu">
            <li><%= link_to "Company Dashboard", companies_path %></li>
            <li><%= link_to "New Company", new_company_path %></li>
            <li><%= link_to "New Employee", new_employee_path %></li>
            <li><%= link_to "Employees", employees_path %></li>
            </li>
          </ul>
          </li>
        <li class="nav-link more"><a href="javascript:void(0)">Admin</a>
          <ul class="submenu">
            <li><%= link_to "Lawgix Dashboard", dashboards_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Admin", '/admin' %></li>
            <li><%= link_to "Settings",new_service_path %></li>
            </li>
          </ul>
          </li>
    </div>
    <div class="navigation-tools">
      <div class="search-bar">
        <div class="search-and-submit">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        </div>
      </div>
      <%= link_to('Sign Out', destroy_user_session_path, :class => "sign-up", :method => :delete) %>
    </div>
  </div>
</header>

app/views/shared/_nav.html.erb
<header class="navigation">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <%= image_tag('lawgix.png') %>
    </a>
    <a href="" class="navigation-menu-button" id="js-mobile-menu">MENU</a>

    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link more"><a href="javascript:void(0)">Projects</a>
          <ul class="submenu">
            <li><%= link_to "New Project", new_project_path %></li>
            <li><%= link_to "Projects", projects_path %></li>
            </li>
          </ul>
        </li>
        <li class="nav-link more"><a href="javascript:void(0)">Leases</a>
          <ul class="submenu">
            <li><%= link_to "Leases", leases_path %>
            </li>
          </ul>
        </li>
        <li class="nav-link more"><a href="javascript:void(0)">Service Requests</a>
          <ul class="submenu">
            <li><%= link_to "Lawgix Dashboard", dashboards_path %></li>
            <li><%= link_to "Request Status", service_transitions_path %>
            <li><%= link_to "Documents", documents_path %>
            </li>
          </ul>
        </li>
      <li class="nav-link more"><a href="javascript:void(0)"> Abstractors</a>
        <ul class="submenu">
          <li><%= link_to "Abstractor Dashboard", absdashes_path %></li>
          <li><%= link_to "Abstractors ", abstractors_path %></li>
          <li><%= link_to "New Abstractor", new_abstractor_path %></li>
      </li>
      </ul>
      </li>
      <li class="nav-link more"><a href="javascript:void(0)"> Lawyers</a>
        <ul class="submenu">
          <li><%= link_to "Lawyers", lawyers_path %></li>
          <li><%= link_to "New Lawyer", new_lawyer_path %></li>
          <li><%= link_to "Law Firm Dashboard", lawyers_path %></li>
          <li><%= link_to "Law Firms", lawfirms_path %></li>
          <li><%= link_to "New Law Firm", new_lawfirm_path %></li>
      </li>
      </ul>
      </li>
      <li class="nav-link more"><a href="javascript:void(0)">Company</a>
        <ul class="submenu">
          <li><%= link_to "Companies", companies_path %></li>
          <li><%= link_to "New Servicer", new_servicer_path %></li>
          <li><%= link_to "New Client", new_client_path %></li>
          <li><%= link_to "Employees", employees_path %></li>
          <li><%= link_to "New Employee", new_employee_path %></li>
      </li>
      </ul>
      </li>
      </li>
      </ul>
      </li>
    </div>
    <div class="navigation-tools">
      <%= link_to('Sign Out', destroy_user_session_path, :class => "sign-up", :method => :delete) %>
    </div>
  </div>
</header>