config/routes.rb
Rails.application.routes.draw do

  root 'visitors#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :projects
  resources :documents
  resources :contacts
  resources :lessors 
  resources :owners
  resources :deeds
  resources :lawfirms
  resources :companies
  resources :servicers
  resources :clients
  resources :employees
  resources :parcels
  resources :leases
  resources :lease_provisons
  resources :lawyers
  resources :services_users
  resources :abstractors
  resources :service_transitions
  resources :dashboards, only: [:index]
  resources :title_abstracts
  resources :abstractor_dashboards, only: [:index]
  resources :absdashes, only: [:index]

  resources :services do
    member do
      put "accept" => "services#accept", as: :accept
    end

    resources :abstractors  do
       member do
         put "assign" => "abstractors#assign", as: :assign
       end
    end
  end

  devise_for :users
  resources :users

end

app/models/absdash.rb
class Absdash < ActiveRecord::Base
  # class for Abstractor Dashboard
end

app/models/client.rb
class Client < Company
  has_many :employees
  has_many :projects
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :employees
  has_and_belongs_to_many :services, through: :companies_services
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :project
  belongs_to :lease
  belongs_to :service
  belongs_to :parcel


   def name
     [first_name, last_name].compact.join(' ')
   end

   def alt_name
     [last_name, first_name].compact.join(', ')
   end

end
 

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/deed.rb
class Deed < ActiveRecord::Base

  has_many :deed_title_abstracts
  has_many :title_abstracts, through: :deed_title_abstracts
  has_many :documents
  accepts_nested_attributes_for  :documents
end

app/models/document.rb
class Document < ActiveRecord::Base

  protokoll :file_name, :pattern => "DOC-%y-%m-####"

  belongs_to :service
  has_many :user_documents
  has_and_belongs_to_many :users, through: :user_documents
  belongs_to :lease
  belongs_to :deed
  belongs_to :title_abstract
  belongs_to :project

  mount_uploader :doc, DocUploader
end

app/models/employee.rb
class Employee < User

  belongs_to :company
  has_many :services, through: :services_users

end

app/models/flow.rb
class Flow < ActiveRecord::Base

 belongs_to :service
 belongs_to :lease



end

app/models/general.rb
class General < Contact

  belongs_to :project
  belongs_to :service

end

app/models/lawfirm.rb
class Lawfirm < ActiveRecord::Base
  has_many :lawyers
  has_many :services

end

app/models/lawyer.rb
class Lawyer < User

  belongs_to :lawfirm
  has_and_belongs_to_many  :services , through: :services_users
  has_and_belongs_to_many :title_abstracts, through: :users_abstracts
end

app/models/lease.rb
class Lease < ActiveRecord::Base

  has_many :services
  has_many :flows
  has_many :parcels
  has_many :documents
  has_many :contacts
  has_many :owners
  has_many :lessors
  has_many :lease_provisons

  belongs_to :project

  accepts_nested_attributes_for :owners
  accepts_nested_attributes_for :lessors
  accepts_nested_attributes_for :parcels
  accepts_nested_attributes_for :documents
  accepts_nested_attributes_for :lease_provisons

end

app/models/lessee.rb
class Lessee < ActiveRecord::Base
  belongs_to :service
  belongs_to :lease
end

app/models/lessor.rb
class Lessor < Contact

  belongs_to :project
  belongs_to :lease
  belongs_to :service

end

app/models/owner.rb
class Owner < Contact

  belongs_to :project 
  belongs_to :lease
  belongs_to :parcel 
  belongs_to :service

end

app/models/parcel.rb
class Parcel < ActiveRecord::Base
  belongs_to :service
  belongs_to :lease
  has_one :title_abstract
  belongs_to :project 
  has_many :owners
  accepts_nested_attributes_for :owners
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :leases
  has_many :services
  has_many :parcels
  has_many :contacts
  has_many :owners
  has_many :lessors
  has_many :title_abstracts
  has_many :documents

  has_paper_trail

end

app/models/service.rb
class Service < ActiveRecord::Base

  protokoll :sr_name, :pattern => "SR-%y-%m-####"

 include Statesman::Adapters::ActiveRecordQueries

 has_many :service_transitions

 has_many :flows
 has_many :parcels
 has_many :contacts
 has_many :lessors
 has_many :documents
 has_many :title_abstracts
 has_and_belongs_to_many :users, through: :services_users
 has_and_belongs_to_many :employees, through: :services_users
 has_and_belongs_to_many :lawyers, through: :services_users
 has_and_belongs_to_many :abstractors, through: :services_users
 has_and_belongs_to_many :companies, through: :services_companies
 has_and_belongs_to_many :servicers, through: :companies_services
 belongs_to :project
 belongs_to :lease

 accepts_nested_attributes_for :documents


 has_paper_trail

 # Initialize the state machine

 def state_machine
  @state_machine ||= RequestStateMachine.new(self, transition_class: ServiceTransition)
 end

 # Optionally delegate some methods
 delegate :can_transition_to?, :transition_to!, :transition_to, :current_state, :allowed_transitions,
          to: :state_machine

 private


 def self.transition_class
  ServiceTransition
 end


 def self.initial_state
   RequestStateMachine.initial_state
 end
end

app/models/servicer.rb
class Servicer < Company
  has_many :employees
  has_many :projects
  has_and_belongs_to_many :services, through: :services_users
  has_and_belongs_to_many :services, through: :companies_services
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  enum role: [:user, :lawgix, :admin]
  has_paper_trail

  belongs_to :company
  has_many :user_documents
  has_and_belongs_to_many :documents, through: :user_documents
  has_and_belongs_to_many :services, through: :services_users


  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  def name
    [first_name, last_name].compact.join(' ')
  end


devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @form = ProjectForm.new(Project.new)
  end

  def show
    @project = Project.find(params[:id])
    # authorize @company
  end

  def index
    @projects = Project.order(created_at: :desc).page_k(params[:page])
  end

  def create
    @form = ProjectForm.new(Project.new)
    if @form.validate(params[:project])
      @form.save
      redirect_to project_path(@form)
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(secure_params)
      redirect_to projects_path, :notice => "Project updated."
    else
      redirect_to projects_path, :alert => "Unable to update Project."
    end
  end

  private

  def secure_params
    params.require(:project).permit!
  end
end

app/views/projects/_abstracts.html.erb
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  </thead>
  <tbody>

  <% @abstracts = @project.title_abstracts %>
  <% @abstracts.each do |abstract| %>
      <tr>
        <td><%= link_to abstract.name, abstract %></td>
        <td><%= abstract.description %></td>
  <% end %>
  </tr>
  </tbody>
</table>

app/views/projects/_contacts.html.erb
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Type</th>
    <ul>
        <li></li>
        <li></li>
    </ul></tr>
  </thead>
  <tbody>
  <% @contacts = @project.contacts %>
  <% @contacts.each do |contact| %>
      <tr>
          <td><%= link_to contact.name, contact %></td>
          <td><%= contact.bus_phone  %>
          <td><%= contact.type %></td> 
        <% end %>
    </tr>
  </tbody>
</table>

app/views/projects/_documents.html.erb
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  </thead>
  <tbody>
  <% @documents = @project.documents %>
  <% @documents.each do |pdoc| %>
    <td><%= link_to pdoc.name, pdoc %></td>
      <td><%= link_to pdoc.doc_type, pdoc %></td>
      <% end %>


  <% @services = @project.services %>
  <% @leases = @project.leases %>
  <% @services.each do |service| %>
      <tr>
            <% @docs = service.documents %>
            <% @docs.each do |doc| %>
                <td><%= link_to doc.name, doc %></td>
                <td><%= link_to doc.doc_type, doc %></td>
      <% end %>
  <% end %>
  </tr>
  <% @leases.each do |lease| %>
      <tr>
        <% @ldocs = lease.documents %>
        <% @ldocs.each do |ldoc| %>
            <td><%= link_to ldoc.name, ldoc %></td>
            <td><%= link_to ldoc.doc_type, ldoc %></td>
        <% end %>
  <% end %>
  </tr>
  </tbody>
</table>

app/views/projects/_leases.html.erb
<table>
  <thead>
  <tr>
    <th>Leases</th>
    <th>State</thB>
    <th>County</th>
  </tr>
  </thead>
  <tbody>

  <% @leases = @project.leases %>
  <% @leases.each do |lease| %>
      <tr>
        <td><%= link_to lease.lease_number, lease %></td>
        <td><%= lease.state %></td>
        <td><%= lease.county %></td>
        <% end %>
     </tr>
  </tbody>
</table>

app/views/projects/_lessors.html.erb
<table>
  <thead>
  <tr>
    <td>Contacts</td>
    <td>Email</td>
    <td>Type</td>
  </tr>
  </thead>
  <tbody>
  <%#
  <%# <% @lessors = @project.lessors %>
  <%# <% @lessors.each do |lessor| %>
  <%#     <tr>
  <%#       <td><%= link_to lessor.last_name, lessor %></td>
  <%#       <td><%= lessor.email %></td>
  <%# <% end %>

  <% @contacts = @project.contacts %>
  <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.last_name, contact %></td>
        <td><%= contact.email %></td>
        <td><%= contact.type %></td>
  <% end %>
  </tr>
  </tbody>
</table>

app/views/projects/_parcels.html.erb
<div id="parcel-index">
  <table>
    <thead>
    <tr>
      <th>Parcel ID</th>
      <th>County</th>
      <th>Township</th>
      <th>Surface Owner</th>
      <th>Lease</th>
    </tr>
    </thead>
    <tbody>
    <% @project.parcels.each do |parcel| %>
        <tr>
          <td><%= link_to parcel.tax_parcel, parcel %></td>
          <td><%= parcel.county %></td>
          <td><%= parcel.tshp %></td>
          <% if parcel.owners   %>
              <% parcel.owners.each do |owner| %>
                <td>  <%= link_to owner.name, owner  %> </td>
              <%  end %>
              <% end  %>
          <% if parcel.lease %>
          <td><%= link_to parcel.lease.lease_number, parcel.lease  %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/projects/_services.html.erb
<table>
  <thead>
  <tr>
    <th>Request</th>
    <th>Description</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>

  <% @services = @project.services %>
  <% @services.each do |service| %>
  <tr>
        <td><%= link_to service.sr_name, service %></td>
        <td><%= link_to service.request, service %></td>
        <td><%= service.current_state %></td>
        <% end %>
     </tr>
  </tbody>
</table>

app/views/projects/create.html.erb
<div class="flex-boxes">
  <div class="flex-box flex-box-full">
    <h1><%= @project.name %></h1>
    <h4><%= @project.description %></h4>
  </div>
  <div class="flex-box flex-box-full">
    <h1> Leases </h1>
    <%= render 'leases', project: @project %>
  </div>
  <div class="flex-box flex-box">
    <h1> Service Requests </h1>
    <%= render 'services', project: @project %>
  </div>
  <div class="flex-box flex-box">
    <h1> Abstracts </h1>
    <%= render 'abstracts', project: @project %>
  </div>
  <div class="flex-box flex-box-full">
    <h1> Documents </h1>
    <%= render 'documents', project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
  <div class="flex-boxes">
    <a class="flex-box flex-box-full">
      <h2 class="flex-title">Lawgix OGX Projects</h2>

  <table class="tables">
    <thead>
    <tr>
      <th>Project Name</th>
      <th>Description</th>
    </tr>
    </thead>
    <tbody>
        <%=   paginate @projects  %>
    <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project %></td>
          <td><%= project.description %></td>
               <% end %>
        </tr>
    </tbody>
  </table>
  </a>
</div>

app/views/projects/new.html.erb
<div class="flex-boxes">
  <div class="flex-box flex-box-full">
  <h1>New Project </h1>
    <%= simple_form_for @form  do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %> 
        <%= f.label :description %>
        <%= f.text_field :description, placeholder: "(location,watershed, etc)" %>
        <%= f.submit 'Create Project' %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="flex-boxes">
  <div class="flex-box flex-box-full">
    <h1><%= @project.name %></h1>
    <h4><%= @project.description %></h4>
  </div>
    <div class="flex-box flex-box-full">
      <h3> <%= link_to "Parcels", parcels_path %> </h3>
      <% @id = @project.id %>
      <%= link_to '<i class="fa fa-plus-square-o fa-2x"></i>'.html_safe, new_parcel_path(project: "#{@id}") %>
      <%= render 'parcels', project: @project %>
    </div>
  <section class="flex-boxes">
  <div class="flex-box flex-box">
      <h3> <%= link_to "Contacts", contacts_path %> </h3>
      <% @id = @project.id %>
      <%= link_to '<i class="fa fa-plus-square-o fa-2x"></i>'.html_safe, new_contact_path(project: "#{@id}") %>
      <%= render 'contacts', project: @project %>
  </div>
    <div class="flex-box flex-box">
    <h3> <%= link_to "Service Requests", services_path %></h3>
    <% @id = @project.id %>
    <%= link_to '<i class="fa fa-plus-square-o fa-2x"></i>'.html_safe, new_service_path(project: "#{@id}") %>
    <%= render 'services', project: @project %>
    </div>
  </section>
  <section class="flex-boxes">
    <div class="flex-box flex-box">
      <% @id = @project.id %>
      <h3> <%= link_to "Leases", leases_path %> </h3>
      <%= link_to '<i class="fa fa-plus-square-o fa-2x"></i>'.html_safe, new_lease_path(project: "#{@id}") %>
      <%= render 'leases', project: @project %>
    </div>
    <div class="flex-box flex-box">
      <h3> <%= link_to "Abstracts", title_abstracts_path %> </h3>
      <% @id = @project.id %>
      <%= link_to '<i class="fa fa-plus-square-o fa-2x"></i>'.html_safe, new_title_abstract_path(project: "#{@id}") %>
      <%= render 'abstracts', project: @project %>
    </div>
  </section>
  <section class="flex-boxes">
    <div class="flex-box flex-box" -full>
      <h3> <%= link_to "Documents", documents_path %> </h3>
      <% @id = @project.id %>
      <%= link_to '<i class="fa fa-plus-square-o fa-2x"></i>'.html_safe, new_document_path(project: "#{@id}") %>
      <%= render 'documents', project: @project %>
    </div>
  </section>
</div>